services:
  - type: web
    name: image-captioning-app
    env: python
    plan: standard
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: TORCH_VERSION
        value: 2.8.0
    disk:
      name: cache
      mountPath: /root/.cache
      sizeGB: 10